<a href="https://colab.research.google.com/github/luisscrc/KNN/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
bills=pd.read_csv("https://gist.githubusercontent.com/javierIA/52184893d57d9a644e2362ee108cfa9e/raw/7297193ea28a0ebed89cb230034a0e62043fe288/bills.csv")

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd

In [ ]:
x=np.array(bills.drop(["Unnamed: 0","is_genuine"],axis=1))
x

array([[171.81, 104.86, 104.95,   4.52,   2.89, 112.83],
       [171.46, 103.36, 103.66,   3.77,   2.99, 113.09],
       [172.69, 104.48, 103.5 ,   4.4 ,   2.94, 113.16],
       ...,
       [171.8 , 104.01, 104.12,   5.51,   3.36, 111.95],
       [172.06, 104.28, 104.06,   5.17,   3.46, 112.25],
       [171.47, 104.15, 103.82,   4.63,   3.37, 112.07]])

In [ ]:
y=np.array(bills["is_genuine"])
y

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

clf=KNeighborsClassifier(n_neighbors=5).fit(x_train,y_train)
clf

KNeighborsClassifier()

In [ ]:

data= np.array([2,3,1,12,21,2]).reshape(1,-1)
print(clf.predict(data))

[0]


In [10]:
# MATRIZ DE CONFUSIÓN para detectar falsos negativos y falsos positivos
# Ayuda a clasificar
from sklearn.metrics import confusion_matrix
y_pred = clf.predict(x_test)
print(y_pred)

conf_mat = confusion_matrix(y_test,y_pred)
print(conf_mat) # [[True Positive, False Positive]
                #  [False Negative, True Negative]]

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 0 1 0 1 0 1 0 1 1 0 1
 1 1 1 1 1 1 0 0 1 1 1 1 0 1 0 0 1 0 0 0 1 0 1 1 0 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 1 1 0 1 1 1 1 1 0 1 0 1 1 1 0 0 0 1 0 1 1 0 0 1 1 1 1 1 0 0 1 1 0
 0 1 0 1 0 0 0 0 1 0 0 1 0 1 1 1 1 1 0 1 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0
 1 1 1 1 1 1 1 0 0 1 1 0 0 0 0 0 0 1 1 1 0 1 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1
 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 0 1
 1 0 1 1 0 0 1 1 0 1 1 1 1 0 0 0 1 0 0 0 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1 0 1
 1 0 0 1 0 1 1 0 1 1 1 1 0 1 0 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 0 1 1 0
 1 0 0 1]
[[110   2]
 [  0 188]]


In [11]:
from sklearn.metrics import accuracy_score
conf_mat = accuracy_score(y_test, y_pred)
print(conf_mat)

0.9933333333333333
